/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BioPassportRegistry__factory } from "./BioPassportRegistry__factory";
export { BioPassportV2__factory } from "./BioPassportV2__factory";
