/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BioPassportRegistry {
  export type CredentialStruct = {
    credentialId: string;
    materialId: string;
    credType: BigNumberish;
    commitmentHash: BytesLike;
    issuer: AddressLike;
    issuerId: string;
    issuedAt: BigNumberish;
    validUntil: BigNumberish;
    artifactCid: string;
    artifactHash: BytesLike;
    revoked: boolean;
  };

  export type CredentialStructOutput = [
    credentialId: string,
    materialId: string,
    credType: bigint,
    commitmentHash: string,
    issuer: string,
    issuerId: string,
    issuedAt: bigint,
    validUntil: bigint,
    artifactCid: string,
    artifactHash: string,
    revoked: boolean
  ] & {
    credentialId: string;
    materialId: string;
    credType: bigint;
    commitmentHash: string;
    issuer: string;
    issuerId: string;
    issuedAt: bigint;
    validUntil: bigint;
    artifactCid: string;
    artifactHash: string;
    revoked: boolean;
  };

  export type MaterialStruct = {
    materialId: string;
    materialType: string;
    metadataHash: BytesLike;
    owner: AddressLike;
    ownerOrg: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type MaterialStructOutput = [
    materialId: string,
    materialType: string,
    metadataHash: string,
    owner: string,
    ownerOrg: string,
    status: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    materialId: string;
    materialType: string;
    metadataHash: string;
    owner: string;
    ownerOrg: string;
    status: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };

  export type TransferStruct = {
    transferId: string;
    materialId: string;
    fromAddress: AddressLike;
    fromOrg: string;
    toAddress: AddressLike;
    toOrg: string;
    shipmentHash: BytesLike;
    timestamp: BigNumberish;
    accepted: boolean;
  };

  export type TransferStructOutput = [
    transferId: string,
    materialId: string,
    fromAddress: string,
    fromOrg: string,
    toAddress: string,
    toOrg: string,
    shipmentHash: string,
    timestamp: bigint,
    accepted: boolean
  ] & {
    transferId: string;
    materialId: string;
    fromAddress: string;
    fromOrg: string;
    toAddress: string;
    toOrg: string;
    shipmentHash: string;
    timestamp: bigint;
    accepted: boolean;
  };
}

export interface BioPassportRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "DEVICE_MANAGER_ROLE"
      | "ISSUER_MANAGER_ROLE"
      | "REGISTRAR_ROLE"
      | "acceptTransfer"
      | "attestationHash"
      | "authorizeIssuer"
      | "batchIssueCredentials"
      | "batchRegisterMaterials"
      | "batchVerifyMaterials"
      | "credentialAttestations"
      | "credentialCount"
      | "credentials"
      | "deviceExists"
      | "devices"
      | "enrollDevice"
      | "getCredential"
      | "getCredentialIds"
      | "getCredentials"
      | "getHistoryAt"
      | "getHistoryCount"
      | "getHistorySlice"
      | "getMaterial"
      | "getRoleAdmin"
      | "getTransfers"
      | "grantRole"
      | "hasRole"
      | "initiateTransfer"
      | "issueCredential"
      | "issueCredentialWithAttestation"
      | "issuerPermissions"
      | "issuerRevokedAt"
      | "materialCount"
      | "materialCredentials"
      | "materialExists"
      | "materialHistory"
      | "materialTransfers"
      | "materials"
      | "pause"
      | "paused"
      | "registerMaterial"
      | "renounceRole"
      | "revokeCredential"
      | "revokeDevice"
      | "revokeIssuer"
      | "revokeRole"
      | "setStatusByAuthority"
      | "setStatusByOwner"
      | "supportsInterface"
      | "transferCount"
      | "unpause"
      | "verifyMaterial"
      | "verifyMaterialAt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationVerified"
      | "CredentialIssued"
      | "CredentialRevoked"
      | "DeviceEnrolled"
      | "DeviceRevocationRecorded"
      | "IssuerAuthorized"
      | "IssuerRevocationRecorded"
      | "MaterialRegistered"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StatusChangedByAuthority"
      | "StatusChangedByOwner"
      | "TransferAccepted"
      | "TransferInitiated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEVICE_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRAR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationHash",
    values: [
      BytesLike,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "batchIssueCredentials",
    values: [
      string[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      string[],
      BytesLike[],
      string[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterMaterials",
    values: [string[], BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyMaterials",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialAttestations",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "credentials", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deviceExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "devices", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "enrollDevice",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentials",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistorySlice",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getMaterial", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [string, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredentialWithAttestation",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      string,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerPermissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerRevokedAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "materialCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "materialCredentials",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "materialExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "materialHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "materialTransfers",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "materials", values: [string]): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMaterial",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDevice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatusByAuthority",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatusByOwner",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyMaterial",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMaterialAt",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEVICE_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRAR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestationHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchIssueCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterMaterials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyMaterials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deviceExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "devices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enrollDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistorySlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredentialWithAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerRevokedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "materials", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStatusByAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStatusByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMaterialAt",
    data: BytesLike
  ): Result;
}

export namespace AttestationVerifiedEvent {
  export type InputTuple = [
    credentialId: string,
    deviceId: BytesLike,
    attestationHash: BytesLike,
    captureTs: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    deviceId: string,
    attestationHash: string,
    captureTs: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    deviceId: string;
    attestationHash: string;
    captureTs: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    credentialId: string,
    materialId: string,
    credType: BigNumberish,
    issuer: AddressLike,
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    materialId: string,
    credType: bigint,
    issuer: string,
    validUntil: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    materialId: string;
    credType: bigint;
    issuer: string;
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    credentialId: string,
    materialId: string,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    materialId: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    materialId: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceEnrolledEvent {
  export type InputTuple = [
    deviceId: BytesLike,
    deviceAddress: AddressLike,
    instrumentType: string,
    enroller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    deviceId: string,
    deviceAddress: string,
    instrumentType: string,
    enroller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    deviceId: string;
    deviceAddress: string;
    instrumentType: string;
    enroller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeviceRevocationRecordedEvent {
  export type InputTuple = [
    deviceId: BytesLike,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    deviceId: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    deviceId: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [
    issuer: AddressLike,
    canIdentity: boolean,
    canQC: boolean,
    canUsageRights: boolean
  ];
  export type OutputTuple = [
    issuer: string,
    canIdentity: boolean,
    canQC: boolean,
    canUsageRights: boolean
  ];
  export interface OutputObject {
    issuer: string;
    canIdentity: boolean;
    canQC: boolean;
    canUsageRights: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevocationRecordedEvent {
  export type InputTuple = [issuer: AddressLike, revokedAt: BigNumberish];
  export type OutputTuple = [issuer: string, revokedAt: bigint];
  export interface OutputObject {
    issuer: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialRegisteredEvent {
  export type InputTuple = [
    materialId: string,
    materialType: string,
    owner: AddressLike,
    ownerOrg: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    materialType: string,
    owner: string,
    ownerOrg: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    materialType: string;
    owner: string;
    ownerOrg: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedByAuthorityEvent {
  export type InputTuple = [
    materialId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    authority: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    oldStatus: bigint,
    newStatus: bigint,
    authority: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    oldStatus: bigint;
    newStatus: bigint;
    authority: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedByOwnerEvent {
  export type InputTuple = [
    materialId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    oldStatus: bigint,
    newStatus: bigint,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    oldStatus: bigint;
    newStatus: bigint;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    transferId: string,
    materialId: string,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: string,
    materialId: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: string;
    materialId: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    transferId: string,
    materialId: string,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: string,
    materialId: string,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: string;
    materialId: string;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BioPassportRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BioPassportRegistry;
  waitForDeployment(): Promise<this>;

  interface: BioPassportRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEVICE_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  acceptTransfer: TypedContractMethod<
    [materialId: string],
    [void],
    "nonpayable"
  >;

  attestationHash: TypedContractMethod<
    [
      deviceId: BytesLike,
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      artifactHash: BytesLike,
      captureTs: BigNumberish
    ],
    [string],
    "view"
  >;

  authorizeIssuer: TypedContractMethod<
    [
      issuer: AddressLike,
      canIdentity: boolean,
      canQC: boolean,
      canUsageRights: boolean
    ],
    [void],
    "nonpayable"
  >;

  batchIssueCredentials: TypedContractMethod<
    [
      materialIds: string[],
      credTypes: BigNumberish[],
      commitmentHashes: BytesLike[],
      validUntils: BigNumberish[],
      artifactCids: string[],
      artifactHashes: BytesLike[],
      issuerIds: string[]
    ],
    [string[]],
    "nonpayable"
  >;

  batchRegisterMaterials: TypedContractMethod<
    [materialTypes: string[], metadataHashes: BytesLike[], ownerOrgs: string[]],
    [string[]],
    "nonpayable"
  >;

  batchVerifyMaterials: TypedContractMethod<
    [materialIds: string[]],
    [[boolean[], string[][]] & { passes: boolean[]; allReasons: string[][] }],
    "view"
  >;

  credentialAttestations: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, string] & {
        deviceId: string;
        captureTs: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;

  credentialCount: TypedContractMethod<[], [bigint], "view">;

  credentials: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        credentialId: string;
        materialId: string;
        credType: bigint;
        commitmentHash: string;
        issuer: string;
        issuerId: string;
        issuedAt: bigint;
        validUntil: bigint;
        artifactCid: string;
        artifactHash: string;
        revoked: boolean;
      }
    ],
    "view"
  >;

  deviceExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  devices: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, bigint] & {
        deviceId: string;
        deviceAddress: string;
        enroller: string;
        enrolledAt: bigint;
        revokedAt: bigint;
        instrumentType: string;
        lastCaptureTs: bigint;
      }
    ],
    "view"
  >;

  enrollDevice: TypedContractMethod<
    [deviceId: BytesLike, deviceAddress: AddressLike, instrumentType: string],
    [void],
    "nonpayable"
  >;

  getCredential: TypedContractMethod<
    [credentialId: string],
    [BioPassportRegistry.CredentialStructOutput],
    "view"
  >;

  getCredentialIds: TypedContractMethod<
    [materialId: string],
    [string[]],
    "view"
  >;

  getCredentials: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.CredentialStructOutput[]],
    "view"
  >;

  getHistoryAt: TypedContractMethod<
    [materialId: string, index: BigNumberish],
    [string],
    "view"
  >;

  getHistoryCount: TypedContractMethod<[materialId: string], [bigint], "view">;

  getHistorySlice: TypedContractMethod<
    [materialId: string, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getMaterial: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.MaterialStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTransfers: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.TransferStructOutput[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [
      materialId: string,
      toAddress: AddressLike,
      toOrg: string,
      shipmentHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  issueCredential: TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string
    ],
    [string],
    "nonpayable"
  >;

  issueCredentialWithAttestation: TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string,
      deviceId: BytesLike,
      captureTs: BigNumberish,
      deviceSig: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  issuerPermissions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, boolean] & {
        isApproved: boolean;
        canIssueIdentity: boolean;
        canIssueQC: boolean;
        canIssueUsageRights: boolean;
      }
    ],
    "view"
  >;

  issuerRevokedAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  materialCount: TypedContractMethod<[], [bigint], "view">;

  materialCredentials: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  materialExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  materialHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  materialTransfers: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean
      ] & {
        transferId: string;
        materialId: string;
        fromAddress: string;
        fromOrg: string;
        toAddress: string;
        toOrg: string;
        shipmentHash: string;
        timestamp: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;

  materials: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        materialId: string;
        materialType: string;
        metadataHash: string;
        owner: string;
        ownerOrg: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerMaterial: TypedContractMethod<
    [materialType: string, metadataHash: BytesLike, ownerOrg: string],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [credentialId: string],
    [void],
    "nonpayable"
  >;

  revokeDevice: TypedContractMethod<
    [deviceId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setStatusByAuthority: TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setStatusByOwner: TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferCount: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyMaterial: TypedContractMethod<
    [materialId: string],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  verifyMaterialAt: TypedContractMethod<
    [materialId: string, atTime: BigNumberish],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEVICE_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRAR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[materialId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attestationHash"
  ): TypedContractMethod<
    [
      deviceId: BytesLike,
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      artifactHash: BytesLike,
      captureTs: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<
    [
      issuer: AddressLike,
      canIdentity: boolean,
      canQC: boolean,
      canUsageRights: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchIssueCredentials"
  ): TypedContractMethod<
    [
      materialIds: string[],
      credTypes: BigNumberish[],
      commitmentHashes: BytesLike[],
      validUntils: BigNumberish[],
      artifactCids: string[],
      artifactHashes: BytesLike[],
      issuerIds: string[]
    ],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchRegisterMaterials"
  ): TypedContractMethod<
    [materialTypes: string[], metadataHashes: BytesLike[], ownerOrgs: string[]],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchVerifyMaterials"
  ): TypedContractMethod<
    [materialIds: string[]],
    [[boolean[], string[][]] & { passes: boolean[]; allReasons: string[][] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "credentialAttestations"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, string] & {
        deviceId: string;
        captureTs: bigint;
        attestationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "credentialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        credentialId: string;
        materialId: string;
        credType: bigint;
        commitmentHash: string;
        issuer: string;
        issuerId: string;
        issuedAt: bigint;
        validUntil: bigint;
        artifactCid: string;
        artifactHash: string;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deviceExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "devices"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, bigint] & {
        deviceId: string;
        deviceAddress: string;
        enroller: string;
        enrolledAt: bigint;
        revokedAt: bigint;
        instrumentType: string;
        lastCaptureTs: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "enrollDevice"
  ): TypedContractMethod<
    [deviceId: BytesLike, deviceAddress: AddressLike, instrumentType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialId: string],
    [BioPassportRegistry.CredentialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialIds"
  ): TypedContractMethod<[materialId: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCredentials"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.CredentialStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistoryAt"
  ): TypedContractMethod<
    [materialId: string, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistoryCount"
  ): TypedContractMethod<[materialId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHistorySlice"
  ): TypedContractMethod<
    [materialId: string, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMaterial"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.MaterialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTransfers"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.TransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [
      materialId: string,
      toAddress: AddressLike,
      toOrg: string,
      shipmentHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueCredentialWithAttestation"
  ): TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string,
      deviceId: BytesLike,
      captureTs: BigNumberish,
      deviceSig: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuerPermissions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, boolean] & {
        isApproved: boolean;
        canIssueIdentity: boolean;
        canIssueQC: boolean;
        canIssueUsageRights: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issuerRevokedAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "materialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "materialCredentials"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "materialExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "materialHistory"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "materialTransfers"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean
      ] & {
        transferId: string;
        materialId: string;
        fromAddress: string;
        fromOrg: string;
        toAddress: string;
        toOrg: string;
        shipmentHash: string;
        timestamp: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "materials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        materialId: string;
        materialType: string;
        metadataHash: string;
        owner: string;
        ownerOrg: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerMaterial"
  ): TypedContractMethod<
    [materialType: string, metadataHash: BytesLike, ownerOrg: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[credentialId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeDevice"
  ): TypedContractMethod<[deviceId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStatusByAuthority"
  ): TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStatusByOwner"
  ): TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyMaterial"
  ): TypedContractMethod<
    [materialId: string],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyMaterialAt"
  ): TypedContractMethod<
    [materialId: string, atTime: BigNumberish],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  getEvent(
    key: "AttestationVerified"
  ): TypedContractEvent<
    AttestationVerifiedEvent.InputTuple,
    AttestationVerifiedEvent.OutputTuple,
    AttestationVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "DeviceEnrolled"
  ): TypedContractEvent<
    DeviceEnrolledEvent.InputTuple,
    DeviceEnrolledEvent.OutputTuple,
    DeviceEnrolledEvent.OutputObject
  >;
  getEvent(
    key: "DeviceRevocationRecorded"
  ): TypedContractEvent<
    DeviceRevocationRecordedEvent.InputTuple,
    DeviceRevocationRecordedEvent.OutputTuple,
    DeviceRevocationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevocationRecorded"
  ): TypedContractEvent<
    IssuerRevocationRecordedEvent.InputTuple,
    IssuerRevocationRecordedEvent.OutputTuple,
    IssuerRevocationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialRegistered"
  ): TypedContractEvent<
    MaterialRegisteredEvent.InputTuple,
    MaterialRegisteredEvent.OutputTuple,
    MaterialRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StatusChangedByAuthority"
  ): TypedContractEvent<
    StatusChangedByAuthorityEvent.InputTuple,
    StatusChangedByAuthorityEvent.OutputTuple,
    StatusChangedByAuthorityEvent.OutputObject
  >;
  getEvent(
    key: "StatusChangedByOwner"
  ): TypedContractEvent<
    StatusChangedByOwnerEvent.InputTuple,
    StatusChangedByOwnerEvent.OutputTuple,
    StatusChangedByOwnerEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AttestationVerified(string,bytes32,bytes32,uint256)": TypedContractEvent<
      AttestationVerifiedEvent.InputTuple,
      AttestationVerifiedEvent.OutputTuple,
      AttestationVerifiedEvent.OutputObject
    >;
    AttestationVerified: TypedContractEvent<
      AttestationVerifiedEvent.InputTuple,
      AttestationVerifiedEvent.OutputTuple,
      AttestationVerifiedEvent.OutputObject
    >;

    "CredentialIssued(string,string,uint8,address,uint256)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(string,string,address,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "DeviceEnrolled(bytes32,address,string,address,uint256)": TypedContractEvent<
      DeviceEnrolledEvent.InputTuple,
      DeviceEnrolledEvent.OutputTuple,
      DeviceEnrolledEvent.OutputObject
    >;
    DeviceEnrolled: TypedContractEvent<
      DeviceEnrolledEvent.InputTuple,
      DeviceEnrolledEvent.OutputTuple,
      DeviceEnrolledEvent.OutputObject
    >;

    "DeviceRevocationRecorded(bytes32,address,uint256)": TypedContractEvent<
      DeviceRevocationRecordedEvent.InputTuple,
      DeviceRevocationRecordedEvent.OutputTuple,
      DeviceRevocationRecordedEvent.OutputObject
    >;
    DeviceRevocationRecorded: TypedContractEvent<
      DeviceRevocationRecordedEvent.InputTuple,
      DeviceRevocationRecordedEvent.OutputTuple,
      DeviceRevocationRecordedEvent.OutputObject
    >;

    "IssuerAuthorized(address,bool,bool,bool)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;

    "IssuerRevocationRecorded(address,uint256)": TypedContractEvent<
      IssuerRevocationRecordedEvent.InputTuple,
      IssuerRevocationRecordedEvent.OutputTuple,
      IssuerRevocationRecordedEvent.OutputObject
    >;
    IssuerRevocationRecorded: TypedContractEvent<
      IssuerRevocationRecordedEvent.InputTuple,
      IssuerRevocationRecordedEvent.OutputTuple,
      IssuerRevocationRecordedEvent.OutputObject
    >;

    "MaterialRegistered(string,string,address,string,uint256)": TypedContractEvent<
      MaterialRegisteredEvent.InputTuple,
      MaterialRegisteredEvent.OutputTuple,
      MaterialRegisteredEvent.OutputObject
    >;
    MaterialRegistered: TypedContractEvent<
      MaterialRegisteredEvent.InputTuple,
      MaterialRegisteredEvent.OutputTuple,
      MaterialRegisteredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StatusChangedByAuthority(string,uint8,uint8,address,bytes32,uint256)": TypedContractEvent<
      StatusChangedByAuthorityEvent.InputTuple,
      StatusChangedByAuthorityEvent.OutputTuple,
      StatusChangedByAuthorityEvent.OutputObject
    >;
    StatusChangedByAuthority: TypedContractEvent<
      StatusChangedByAuthorityEvent.InputTuple,
      StatusChangedByAuthorityEvent.OutputTuple,
      StatusChangedByAuthorityEvent.OutputObject
    >;

    "StatusChangedByOwner(string,uint8,uint8,bytes32,uint256)": TypedContractEvent<
      StatusChangedByOwnerEvent.InputTuple,
      StatusChangedByOwnerEvent.OutputTuple,
      StatusChangedByOwnerEvent.OutputObject
    >;
    StatusChangedByOwner: TypedContractEvent<
      StatusChangedByOwnerEvent.InputTuple,
      StatusChangedByOwnerEvent.OutputTuple,
      StatusChangedByOwnerEvent.OutputObject
    >;

    "TransferAccepted(string,string,address,uint256)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferInitiated(string,string,address,address,uint256)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
