/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BioPassportV2 {
  export type AssetRecordStruct = {
    assetIdHash: BytesLike;
    pointer: string;
    registrar: AddressLike;
    createdAt: BigNumberish;
    latestCredentialHash: BytesLike;
    exists: boolean;
  };

  export type AssetRecordStructOutput = [
    assetIdHash: string,
    pointer: string,
    registrar: string,
    createdAt: bigint,
    latestCredentialHash: string,
    exists: boolean
  ] & {
    assetIdHash: string;
    pointer: string;
    registrar: string;
    createdAt: bigint;
    latestCredentialHash: string;
    exists: boolean;
  };

  export type CredentialRecordStruct = {
    assetIdHash: BytesLike;
    credentialHash: BytesLike;
    prevHash: BytesLike;
    evidenceRoot: BytesLike;
    pointer: string;
    issuer: AddressLike;
    issuedAt: BigNumberish;
    exists: boolean;
  };

  export type CredentialRecordStructOutput = [
    assetIdHash: string,
    credentialHash: string,
    prevHash: string,
    evidenceRoot: string,
    pointer: string,
    issuer: string,
    issuedAt: bigint,
    exists: boolean
  ] & {
    assetIdHash: string;
    credentialHash: string;
    prevHash: string;
    evidenceRoot: string;
    pointer: string;
    issuer: string;
    issuedAt: bigint;
    exists: boolean;
  };

  export type ExceptionRecordStruct = {
    exceptionId: BigNumberish;
    assetIdHash: BytesLike;
    relatedCredentialHash: BytesLike;
    reasonCode: BigNumberish;
    detailsPointer: string;
    openedBy: AddressLike;
    openedAt: BigNumberish;
    closed: boolean;
    closedBy: AddressLike;
    closedAt: BigNumberish;
    resolutionPointer: string;
  };

  export type ExceptionRecordStructOutput = [
    exceptionId: bigint,
    assetIdHash: string,
    relatedCredentialHash: string,
    reasonCode: bigint,
    detailsPointer: string,
    openedBy: string,
    openedAt: bigint,
    closed: boolean,
    closedBy: string,
    closedAt: bigint,
    resolutionPointer: string
  ] & {
    exceptionId: bigint;
    assetIdHash: string;
    relatedCredentialHash: string;
    reasonCode: bigint;
    detailsPointer: string;
    openedBy: string;
    openedAt: bigint;
    closed: boolean;
    closedBy: string;
    closedAt: bigint;
    resolutionPointer: string;
  };
}

export interface BioPassportV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_ROLE"
      | "assets"
      | "closeException"
      | "credentialCount"
      | "credentials"
      | "exceptions"
      | "getAsset"
      | "getCredential"
      | "getCredentialCount"
      | "getException"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isAuditor"
      | "isIssuer"
      | "issueCredential"
      | "nextExceptionId"
      | "openException"
      | "registerAsset"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "verifyChainLinkage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRegistered"
      | "CredentialIssued"
      | "ExceptionClosed"
      | "ExceptionOpened"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "closeException",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "exceptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAsset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getException",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuditor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "nextExceptionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openException",
    values: [BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyChainLinkage",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeException",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exceptions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getException",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAuditor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextExceptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openException",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyChainLinkage",
    data: BytesLike
  ): Result;
}

export namespace AssetRegisteredEvent {
  export type InputTuple = [
    assetIdHash: BytesLike,
    pointer: string,
    registrar: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assetIdHash: string,
    pointer: string,
    registrar: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assetIdHash: string;
    pointer: string;
    registrar: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    assetIdHash: BytesLike,
    credentialHash: BytesLike,
    prevHash: BytesLike,
    evidenceRoot: BytesLike,
    pointer: string,
    issuer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    assetIdHash: string,
    credentialHash: string,
    prevHash: string,
    evidenceRoot: string,
    pointer: string,
    issuer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    assetIdHash: string;
    credentialHash: string;
    prevHash: string;
    evidenceRoot: string;
    pointer: string;
    issuer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExceptionClosedEvent {
  export type InputTuple = [
    exceptionId: BigNumberish,
    resolutionPointer: string,
    closedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    exceptionId: bigint,
    resolutionPointer: string,
    closedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    exceptionId: bigint;
    resolutionPointer: string;
    closedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExceptionOpenedEvent {
  export type InputTuple = [
    exceptionId: BigNumberish,
    assetIdHash: BytesLike,
    relatedCredentialHash: BytesLike,
    reasonCode: BigNumberish,
    detailsPointer: string,
    openedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    exceptionId: bigint,
    assetIdHash: string,
    relatedCredentialHash: string,
    reasonCode: bigint,
    detailsPointer: string,
    openedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    exceptionId: bigint;
    assetIdHash: string;
    relatedCredentialHash: string;
    reasonCode: bigint;
    detailsPointer: string;
    openedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BioPassportV2 extends BaseContract {
  connect(runner?: ContractRunner | null): BioPassportV2;
  waitForDeployment(): Promise<this>;

  interface: BioPassportV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_ROLE: TypedContractMethod<[], [string], "view">;

  assets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, boolean] & {
        assetIdHash: string;
        pointer: string;
        registrar: string;
        createdAt: bigint;
        latestCredentialHash: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  closeException: TypedContractMethod<
    [exceptionId: BigNumberish, resolutionPointer: string],
    [void],
    "nonpayable"
  >;

  credentialCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        assetIdHash: string;
        credentialHash: string;
        prevHash: string;
        evidenceRoot: string;
        pointer: string;
        issuer: string;
        issuedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  exceptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        string
      ] & {
        exceptionId: bigint;
        assetIdHash: string;
        relatedCredentialHash: string;
        reasonCode: bigint;
        detailsPointer: string;
        openedBy: string;
        openedAt: bigint;
        closed: boolean;
        closedBy: string;
        closedAt: bigint;
        resolutionPointer: string;
      }
    ],
    "view"
  >;

  getAsset: TypedContractMethod<
    [assetIdHash: BytesLike],
    [BioPassportV2.AssetRecordStructOutput],
    "view"
  >;

  getCredential: TypedContractMethod<
    [credentialHash: BytesLike],
    [BioPassportV2.CredentialRecordStructOutput],
    "view"
  >;

  getCredentialCount: TypedContractMethod<
    [assetIdHash: BytesLike],
    [bigint],
    "view"
  >;

  getException: TypedContractMethod<
    [exceptionId: BigNumberish],
    [BioPassportV2.ExceptionRecordStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAuditor: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isIssuer: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  issueCredential: TypedContractMethod<
    [
      assetIdHash: BytesLike,
      credentialHash: BytesLike,
      prevHash: BytesLike,
      evidenceRoot: BytesLike,
      pointer: string
    ],
    [void],
    "nonpayable"
  >;

  nextExceptionId: TypedContractMethod<[], [bigint], "view">;

  openException: TypedContractMethod<
    [
      assetIdHash: BytesLike,
      relatedCredentialHash: BytesLike,
      reasonCode: BigNumberish,
      detailsPointer: string
    ],
    [bigint],
    "nonpayable"
  >;

  registerAsset: TypedContractMethod<
    [assetIdHash: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  verifyChainLinkage: TypedContractMethod<
    [credentialHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, boolean] & {
        assetIdHash: string;
        pointer: string;
        registrar: string;
        createdAt: bigint;
        latestCredentialHash: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeException"
  ): TypedContractMethod<
    [exceptionId: BigNumberish, resolutionPointer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "credentialCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        assetIdHash: string;
        credentialHash: string;
        prevHash: string;
        evidenceRoot: string;
        pointer: string;
        issuer: string;
        issuedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "exceptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        string
      ] & {
        exceptionId: bigint;
        assetIdHash: string;
        relatedCredentialHash: string;
        reasonCode: bigint;
        detailsPointer: string;
        openedBy: string;
        openedAt: bigint;
        closed: boolean;
        closedBy: string;
        closedAt: bigint;
        resolutionPointer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAsset"
  ): TypedContractMethod<
    [assetIdHash: BytesLike],
    [BioPassportV2.AssetRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialHash: BytesLike],
    [BioPassportV2.CredentialRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialCount"
  ): TypedContractMethod<[assetIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getException"
  ): TypedContractMethod<
    [exceptionId: BigNumberish],
    [BioPassportV2.ExceptionRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuditor"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isIssuer"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      assetIdHash: BytesLike,
      credentialHash: BytesLike,
      prevHash: BytesLike,
      evidenceRoot: BytesLike,
      pointer: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextExceptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openException"
  ): TypedContractMethod<
    [
      assetIdHash: BytesLike,
      relatedCredentialHash: BytesLike,
      reasonCode: BigNumberish,
      detailsPointer: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAsset"
  ): TypedContractMethod<
    [assetIdHash: BytesLike, pointer: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyChainLinkage"
  ): TypedContractMethod<[credentialHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "AssetRegistered"
  ): TypedContractEvent<
    AssetRegisteredEvent.InputTuple,
    AssetRegisteredEvent.OutputTuple,
    AssetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "ExceptionClosed"
  ): TypedContractEvent<
    ExceptionClosedEvent.InputTuple,
    ExceptionClosedEvent.OutputTuple,
    ExceptionClosedEvent.OutputObject
  >;
  getEvent(
    key: "ExceptionOpened"
  ): TypedContractEvent<
    ExceptionOpenedEvent.InputTuple,
    ExceptionOpenedEvent.OutputTuple,
    ExceptionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "AssetRegistered(bytes32,string,address,uint64)": TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;
    AssetRegistered: TypedContractEvent<
      AssetRegisteredEvent.InputTuple,
      AssetRegisteredEvent.OutputTuple,
      AssetRegisteredEvent.OutputObject
    >;

    "CredentialIssued(bytes32,bytes32,bytes32,bytes32,string,address,uint64)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "ExceptionClosed(uint256,string,address,uint64)": TypedContractEvent<
      ExceptionClosedEvent.InputTuple,
      ExceptionClosedEvent.OutputTuple,
      ExceptionClosedEvent.OutputObject
    >;
    ExceptionClosed: TypedContractEvent<
      ExceptionClosedEvent.InputTuple,
      ExceptionClosedEvent.OutputTuple,
      ExceptionClosedEvent.OutputObject
    >;

    "ExceptionOpened(uint256,bytes32,bytes32,uint8,string,address,uint64)": TypedContractEvent<
      ExceptionOpenedEvent.InputTuple,
      ExceptionOpenedEvent.OutputTuple,
      ExceptionOpenedEvent.OutputObject
    >;
    ExceptionOpened: TypedContractEvent<
      ExceptionOpenedEvent.InputTuple,
      ExceptionOpenedEvent.OutputTuple,
      ExceptionOpenedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
