/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BioPassportRegistry {
  export type CredentialStruct = {
    credentialId: string;
    materialId: string;
    credType: BigNumberish;
    commitmentHash: BytesLike;
    issuer: AddressLike;
    issuerId: string;
    issuedAt: BigNumberish;
    validUntil: BigNumberish;
    artifactCid: string;
    artifactHash: BytesLike;
    revoked: boolean;
  };

  export type CredentialStructOutput = [
    credentialId: string,
    materialId: string,
    credType: bigint,
    commitmentHash: string,
    issuer: string,
    issuerId: string,
    issuedAt: bigint,
    validUntil: bigint,
    artifactCid: string,
    artifactHash: string,
    revoked: boolean
  ] & {
    credentialId: string;
    materialId: string;
    credType: bigint;
    commitmentHash: string;
    issuer: string;
    issuerId: string;
    issuedAt: bigint;
    validUntil: bigint;
    artifactCid: string;
    artifactHash: string;
    revoked: boolean;
  };

  export type MaterialStruct = {
    materialId: string;
    materialType: string;
    metadataHash: BytesLike;
    owner: AddressLike;
    ownerOrg: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type MaterialStructOutput = [
    materialId: string,
    materialType: string,
    metadataHash: string,
    owner: string,
    ownerOrg: string,
    status: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    materialId: string;
    materialType: string;
    metadataHash: string;
    owner: string;
    ownerOrg: string;
    status: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };

  export type TransferStruct = {
    transferId: string;
    materialId: string;
    fromAddress: AddressLike;
    fromOrg: string;
    toAddress: AddressLike;
    toOrg: string;
    shipmentHash: BytesLike;
    timestamp: BigNumberish;
    accepted: boolean;
  };

  export type TransferStructOutput = [
    transferId: string,
    materialId: string,
    fromAddress: string,
    fromOrg: string,
    toAddress: string,
    toOrg: string,
    shipmentHash: string,
    timestamp: bigint,
    accepted: boolean
  ] & {
    transferId: string;
    materialId: string;
    fromAddress: string;
    fromOrg: string;
    toAddress: string;
    toOrg: string;
    shipmentHash: string;
    timestamp: bigint;
    accepted: boolean;
  };
}

export interface BioPassportRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "admin"
      | "authorizeIssuer"
      | "credentialCount"
      | "credentials"
      | "getCredential"
      | "getCredentialIds"
      | "getCredentials"
      | "getHistoryAt"
      | "getHistoryCount"
      | "getHistorySlice"
      | "getMaterial"
      | "getTransfers"
      | "initiateTransfer"
      | "issueCredential"
      | "issuerPermissions"
      | "issuerRevokedAt"
      | "materialCount"
      | "materialCredentials"
      | "materialExists"
      | "materialHistory"
      | "materialTransfers"
      | "materials"
      | "registerMaterial"
      | "revokeCredential"
      | "revokeIssuer"
      | "setStatusByAuthority"
      | "setStatusByOwner"
      | "transferCount"
      | "verifyMaterial"
      | "verifyMaterialAt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialRevoked"
      | "IssuerAuthorized"
      | "IssuerRevocationRecorded"
      | "MaterialRegistered"
      | "StatusChangedByAuthority"
      | "StatusChangedByOwner"
      | "TransferAccepted"
      | "TransferInitiated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "credentials", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialIds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentials",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoryCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistorySlice",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getMaterial", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTransfers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [string, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerPermissions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerRevokedAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "materialCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "materialCredentials",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "materialExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "materialHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "materialTransfers",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "materials", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerMaterial",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatusByAuthority",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStatusByOwner",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMaterial",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMaterialAt",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistorySlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerRevokedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "materialTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "materials", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStatusByAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStatusByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMaterial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMaterialAt",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    credentialId: string,
    materialId: string,
    credType: BigNumberish,
    issuer: AddressLike,
    validUntil: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    materialId: string,
    credType: bigint,
    issuer: string,
    validUntil: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    materialId: string;
    credType: bigint;
    issuer: string;
    validUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    credentialId: string,
    materialId: string,
    revoker: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    materialId: string,
    revoker: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    materialId: string;
    revoker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [
    issuer: AddressLike,
    canIdentity: boolean,
    canQC: boolean,
    canUsageRights: boolean
  ];
  export type OutputTuple = [
    issuer: string,
    canIdentity: boolean,
    canQC: boolean,
    canUsageRights: boolean
  ];
  export interface OutputObject {
    issuer: string;
    canIdentity: boolean;
    canQC: boolean;
    canUsageRights: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevocationRecordedEvent {
  export type InputTuple = [issuer: AddressLike, revokedAt: BigNumberish];
  export type OutputTuple = [issuer: string, revokedAt: bigint];
  export interface OutputObject {
    issuer: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaterialRegisteredEvent {
  export type InputTuple = [
    materialId: string,
    materialType: string,
    owner: AddressLike,
    ownerOrg: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    materialType: string,
    owner: string,
    ownerOrg: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    materialType: string;
    owner: string;
    ownerOrg: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedByAuthorityEvent {
  export type InputTuple = [
    materialId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    authority: AddressLike,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    oldStatus: bigint,
    newStatus: bigint,
    authority: string,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    oldStatus: bigint;
    newStatus: bigint;
    authority: string;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusChangedByOwnerEvent {
  export type InputTuple = [
    materialId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    reasonHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    materialId: string,
    oldStatus: bigint,
    newStatus: bigint,
    reasonHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    materialId: string;
    oldStatus: bigint;
    newStatus: bigint;
    reasonHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    transferId: string,
    materialId: string,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: string,
    materialId: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: string;
    materialId: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    transferId: string,
    materialId: string,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transferId: string,
    materialId: string,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    transferId: string;
    materialId: string;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BioPassportRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BioPassportRegistry;
  waitForDeployment(): Promise<this>;

  interface: BioPassportRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [materialId: string],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  authorizeIssuer: TypedContractMethod<
    [
      issuer: AddressLike,
      canIdentity: boolean,
      canQC: boolean,
      canUsageRights: boolean
    ],
    [void],
    "nonpayable"
  >;

  credentialCount: TypedContractMethod<[], [bigint], "view">;

  credentials: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        credentialId: string;
        materialId: string;
        credType: bigint;
        commitmentHash: string;
        issuer: string;
        issuerId: string;
        issuedAt: bigint;
        validUntil: bigint;
        artifactCid: string;
        artifactHash: string;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getCredential: TypedContractMethod<
    [credentialId: string],
    [BioPassportRegistry.CredentialStructOutput],
    "view"
  >;

  getCredentialIds: TypedContractMethod<
    [materialId: string],
    [string[]],
    "view"
  >;

  getCredentials: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.CredentialStructOutput[]],
    "view"
  >;

  getHistoryAt: TypedContractMethod<
    [materialId: string, index: BigNumberish],
    [string],
    "view"
  >;

  getHistoryCount: TypedContractMethod<[materialId: string], [bigint], "view">;

  getHistorySlice: TypedContractMethod<
    [materialId: string, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getMaterial: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.MaterialStructOutput],
    "view"
  >;

  getTransfers: TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.TransferStructOutput[]],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [
      materialId: string,
      toAddress: AddressLike,
      toOrg: string,
      shipmentHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  issueCredential: TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string
    ],
    [string],
    "nonpayable"
  >;

  issuerPermissions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, boolean] & {
        isApproved: boolean;
        canIssueIdentity: boolean;
        canIssueQC: boolean;
        canIssueUsageRights: boolean;
      }
    ],
    "view"
  >;

  issuerRevokedAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  materialCount: TypedContractMethod<[], [bigint], "view">;

  materialCredentials: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  materialExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  materialHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [string],
    "view"
  >;

  materialTransfers: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean
      ] & {
        transferId: string;
        materialId: string;
        fromAddress: string;
        fromOrg: string;
        toAddress: string;
        toOrg: string;
        shipmentHash: string;
        timestamp: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;

  materials: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        materialId: string;
        materialType: string;
        metadataHash: string;
        owner: string;
        ownerOrg: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  registerMaterial: TypedContractMethod<
    [materialType: string, metadataHash: BytesLike, ownerOrg: string],
    [string],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [credentialId: string],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  setStatusByAuthority: TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setStatusByOwner: TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferCount: TypedContractMethod<[], [bigint], "view">;

  verifyMaterial: TypedContractMethod<
    [materialId: string],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  verifyMaterialAt: TypedContractMethod<
    [materialId: string, atTime: BigNumberish],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[materialId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<
    [
      issuer: AddressLike,
      canIdentity: boolean,
      canQC: boolean,
      canUsageRights: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "credentialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        boolean
      ] & {
        credentialId: string;
        materialId: string;
        credType: bigint;
        commitmentHash: string;
        issuer: string;
        issuerId: string;
        issuedAt: bigint;
        validUntil: bigint;
        artifactCid: string;
        artifactHash: string;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialId: string],
    [BioPassportRegistry.CredentialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialIds"
  ): TypedContractMethod<[materialId: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCredentials"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.CredentialStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistoryAt"
  ): TypedContractMethod<
    [materialId: string, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistoryCount"
  ): TypedContractMethod<[materialId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHistorySlice"
  ): TypedContractMethod<
    [materialId: string, offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMaterial"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.MaterialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfers"
  ): TypedContractMethod<
    [materialId: string],
    [BioPassportRegistry.TransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [
      materialId: string,
      toAddress: AddressLike,
      toOrg: string,
      shipmentHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      materialId: string,
      credType: BigNumberish,
      commitmentHash: BytesLike,
      validUntil: BigNumberish,
      artifactCid: string,
      artifactHash: BytesLike,
      issuerId: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuerPermissions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean, boolean] & {
        isApproved: boolean;
        canIssueIdentity: boolean;
        canIssueQC: boolean;
        canIssueUsageRights: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issuerRevokedAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "materialCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "materialCredentials"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "materialExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "materialHistory"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "materialTransfers"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean
      ] & {
        transferId: string;
        materialId: string;
        fromAddress: string;
        fromOrg: string;
        toAddress: string;
        toOrg: string;
        shipmentHash: string;
        timestamp: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "materials"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, bigint, bigint] & {
        materialId: string;
        materialType: string;
        metadataHash: string;
        owner: string;
        ownerOrg: string;
        status: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerMaterial"
  ): TypedContractMethod<
    [materialType: string, metadataHash: BytesLike, ownerOrg: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[credentialId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStatusByAuthority"
  ): TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStatusByOwner"
  ): TypedContractMethod<
    [materialId: string, newStatus: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyMaterial"
  ): TypedContractMethod<
    [materialId: string],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyMaterialAt"
  ): TypedContractMethod<
    [materialId: string, atTime: BigNumberish],
    [[boolean, string[]] & { pass: boolean; reasons: string[] }],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevocationRecorded"
  ): TypedContractEvent<
    IssuerRevocationRecordedEvent.InputTuple,
    IssuerRevocationRecordedEvent.OutputTuple,
    IssuerRevocationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MaterialRegistered"
  ): TypedContractEvent<
    MaterialRegisteredEvent.InputTuple,
    MaterialRegisteredEvent.OutputTuple,
    MaterialRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StatusChangedByAuthority"
  ): TypedContractEvent<
    StatusChangedByAuthorityEvent.InputTuple,
    StatusChangedByAuthorityEvent.OutputTuple,
    StatusChangedByAuthorityEvent.OutputObject
  >;
  getEvent(
    key: "StatusChangedByOwner"
  ): TypedContractEvent<
    StatusChangedByOwnerEvent.InputTuple,
    StatusChangedByOwnerEvent.OutputTuple,
    StatusChangedByOwnerEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(string,string,uint8,address,uint256)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(string,string,address,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerAuthorized(address,bool,bool,bool)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;

    "IssuerRevocationRecorded(address,uint256)": TypedContractEvent<
      IssuerRevocationRecordedEvent.InputTuple,
      IssuerRevocationRecordedEvent.OutputTuple,
      IssuerRevocationRecordedEvent.OutputObject
    >;
    IssuerRevocationRecorded: TypedContractEvent<
      IssuerRevocationRecordedEvent.InputTuple,
      IssuerRevocationRecordedEvent.OutputTuple,
      IssuerRevocationRecordedEvent.OutputObject
    >;

    "MaterialRegistered(string,string,address,string,uint256)": TypedContractEvent<
      MaterialRegisteredEvent.InputTuple,
      MaterialRegisteredEvent.OutputTuple,
      MaterialRegisteredEvent.OutputObject
    >;
    MaterialRegistered: TypedContractEvent<
      MaterialRegisteredEvent.InputTuple,
      MaterialRegisteredEvent.OutputTuple,
      MaterialRegisteredEvent.OutputObject
    >;

    "StatusChangedByAuthority(string,uint8,uint8,address,bytes32,uint256)": TypedContractEvent<
      StatusChangedByAuthorityEvent.InputTuple,
      StatusChangedByAuthorityEvent.OutputTuple,
      StatusChangedByAuthorityEvent.OutputObject
    >;
    StatusChangedByAuthority: TypedContractEvent<
      StatusChangedByAuthorityEvent.InputTuple,
      StatusChangedByAuthorityEvent.OutputTuple,
      StatusChangedByAuthorityEvent.OutputObject
    >;

    "StatusChangedByOwner(string,uint8,uint8,bytes32,uint256)": TypedContractEvent<
      StatusChangedByOwnerEvent.InputTuple,
      StatusChangedByOwnerEvent.OutputTuple,
      StatusChangedByOwnerEvent.OutputObject
    >;
    StatusChangedByOwner: TypedContractEvent<
      StatusChangedByOwnerEvent.InputTuple,
      StatusChangedByOwnerEvent.OutputTuple,
      StatusChangedByOwnerEvent.OutputObject
    >;

    "TransferAccepted(string,string,address,uint256)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferInitiated(string,string,address,address,uint256)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
  };
}
