/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BioPassportRegistry } from "./BioPassportRegistry";
export type { BioPassportV2 } from "./BioPassportV2";
